In [1]:
import pandas
import numpy

In [2]:
fl = "/Users/simondi/PROJECTS/target_infect_x_project/src/tix-analysis/data/kmeans-transformed-clusters/cluster-0.tsv"

In [2]:
fl2 = "/Users/simondi/PROJECTS/target_infect_x_project/src/tix-analysis/data/kmeans-fit-K2_sse.tsv"

In [3]:
d =  pandas.read_csv(fl2, sep="\t")

In [12]:
d

          SSE   N   P  K
0  822.099098  94  15  2

In [5]:
matr = pandas.read_csv(fl, sep="\t", nrows=1000, usecols=lambda x: x.startswith("f_"))

In [6]:
matr

,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,f_9,f_10,f_11,f_12,f_13,f_14
0,-1.003658,0.085274,0.197032,-0.964995,1.129380,1.042910,-0.171486,-0.878978,-1.192508,0.429975,0.648306,-0.435122,1.048247,2.110219,-0.274423
1,0.784961,1.559620,-0.146064,0.521765,1.545419,-0.700311,0.017749,-1.454793,-0.588712,0.450029,1.308061,-1.114968,1.491880,1.391397,-0.913096
2,-0.234562,2.220134,0.220290,0.584940,0.786403,-0.784821,-0.016866,-2.134568,-0.911289,0.624639,2.210342,-0.507912,1.010805,1.878128,-0.750670
3,-0.294212,0.956728,0.574683,1.709418,1.256480,0.821547,0.071829,-1.332389,0.032115,1.703608,2.188919,-0.478859,0.051450,0.788928,-0.305185
4,0.185288,0.979411,0.152929,0.447373,0.568263,-1.179948,0.088387,-2.727045,-0.467840,1.080001,1.725717,-1.139752,0.192637,1.281680,-0.298778
5,-1.014659,1.325111,0.025889,0.700651,1.193322,-0.390503,0.012633,0.081866,-0.978086,0.216549,0.182372,-1.453203,1.170124,0.194679,0.683806
6,-0.085144,1.398571,-0.115649,0.535643,1.192458,-1.222086,0.034654,-2.295123,-0.732105,0.740418,1.511971,-1.314843,0.309145,1.529738,-0.835309
7,-0.404906,1.505735,-0.184642,0.697797,0.578283,0.275995,-0.108729,-1.272301,-0.526603,-0.204011,1.413424,1.115193,-0.353671,0.677483,-0.563640
8,-1.868028,1.884044,0.273870,0.304406,0.900401,0.058493,-0.080385,-2.540364,-1.022873,0.770196,1.699794,0.038893,1.541319,1.554987,-0.312091
9,-0.207894,1.862896,-0.773403,-0.067005,1.146480,1.081343,-0.032722,-0.384469,-1.025615,-0.838569,0.665042,-0.536419,0.184312,1.893046,-0.912432
10,-0.461663,0.386885,0.505867,0.464756,0.568083,-0.609192,0.179086,-1.614619,0.005040,1.589010,1.836605,-1.520439,-0.262517,0.275875,0.790417
11,-0.636856,-1.097917,0.771446,-1.166651,-0.724793,1.772356,0.155142,-2.633993,-0.448762,1.859600,0.510716,-1.011424,1.330123,2.111343,0.768465
12,-1.453983,0.665786,-0.272464,-1.509885,0.407938,0.667701,-0.229167,-0.777195,-1.097577,0.070901,1.120751,0.166049,1.061666,1.883879,0.082029

In [7]:
matr["f_0"]

0    -1.003658
1     0.784961
2    -0.234562
3    -0.294212
4     0.185288
5    -1.014659
6    -0.085144
7    -0.404906
8    -1.868028
9    -0.207894
10   -0.461663
11   -0.636856
12   -1.453983
Name: f_0, dtype: float64

In [17]:

matr["features"].split(",", expand=True).as_matrix().astype(numpy.float64)

AttributeError: 'Series' object has no attribute 'split'